repos:
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # Use the latest commit on the master branch
    hooks:
      - id: flake8
        args:
          - --ignore=E501,F401,E203,W503,E741
  - repo: https://github.com/psf/black
    rev: '23.11.0'  # Use the latest commit on the master branch
    hooks:
      - id: black
        args: ['src/unicorn_baseline']
